name: Test
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18, 20, 22, 24]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          check-latest: true
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: |
          corepack enable
          pnpm install
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
      - name: Check package
        run: pnpm check
